:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]

A promise is an object that may produce a single value some time in the future: either a resolved value, or a reason that it’s not resolved (e.g., a network error occurred). A promise may be in one of 3 possible states: fulfilled, rejected, or pending. Promise users can attach callbacks to handle the fulfilled value or the reason for rejection.

Promises are eager, meaning that a promise will start doing whatever task you give it as soon as the promise constructor is invoked. If you need lazy, check out observables or tasks.

== Promise rules: 

* A promise or “thenable” is an object that supplies a standard-compliant .then() method.
* A pending promise may transition into a fulfilled or rejected state.
* A fulfilled or rejected promise is settled, and must not transition into any other state.
* Once a promise is settled, it must have a value (which may be undefined). That value must not change.
* Every promise must supply a .then() method with the following signature: 
`promise.then(
  onFulfilled?: Function,
  onRejected?: Function
) => Promise`
* Both onFulfilled() and onRejected() are optional.
* If the arguments supplied are not functions, they must be ignored.
* onFulfilled() will be called after the promise is fulfilled, with the promise’s value as the first argument.
* onRejected() will be called after the promise is rejected, with the reason for rejection as the first argument. The reason may be any valid JavaScript value, but because rejections are essentially synonymous with exceptions, I recommend using Error objects.
* Neither onFulfilled() nor onRejected() may be called more than once.
* then() may be called many times on the same promise. In other words, a promise can be used to aggregate callbacks.
* .then() must return a new promise, promise2.

== AJAX call packages 

=== JQuery.ajax()

* only push and get request

=== XMLHTTPRequest

=== Axios
* promise based
* Able to cancel a request
* Provide upload progress tool
* Multiple get requests


=== Fetch
* promise based

=== Superagent
* promise based
